#!/bin/bash
git pull
container_id=$(sudo docker container ls | grep discordegld | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
	sudo docker container stop $container_id
fi
sudo docker image rm --force discordegld
sudo docker build -t discordegld .
sudo docker run -d -v db_discordegld:/app/db discordegld
# sudo docker run -it -v db_discordhort:/app/db discordhort /bin/bash
