#!/bin/bash

git remote update

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

name=discordegld

container_id=$(sudo docker container ls | grep "$name" | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
    sudo docker container stop $container_id
fi

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
    git pull
    sudo docker image rm --force "$name"
    sudo docker build --no-cache -t "$name" .
fi

name="discordegld"; sudo docker run -d -v /root/discord_egld/db:/app/db "$name"
# sudo docker run -it -v /root/discord_egld/db:/app/db/ "$name" /bin/bash
